using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Prm;

namespace Prm
{
    internal class RentalList
    {
        public string PokemonName { get; set; }
        public string ItemName { get; set; }


        public static class PokemonData
        {
            public static List<RentalList> GetRentalList()
            {
                List<RentalList> PokemonList = new List<RentalList>
                {
                    new RentalList { PokemonName = "ミネズミ", ItemName = "クラボのみ" },
                    new RentalList { PokemonName = "フシデ", ItemName = "カゴのみ" },
                    new RentalList { PokemonName = "マメパト", ItemName = "ソクノのみ" },
                    new RentalList { PokemonName = "ヨーテリー", ItemName = "ヨプのみ" },
                    new RentalList { PokemonName = "ヒトモシ", ItemName = "キーのみ" },
                    new RentalList { PokemonName = "ダンゴロ", ItemName = "シュカのみ" },
                    new RentalList { PokemonName = "モンメン", ItemName = "おおきなねっこ" },
                    new RentalList { PokemonName = "チュリネ", ItemName = "キーのみ" },
                    new RentalList { PokemonName = "コジョフー", ItemName = "クラボのみ" },
                    new RentalList { PokemonName = "チョロネコ", ItemName = "くろいメガネ" },
                    new RentalList { PokemonName = "ゴチム", ItemName = "キーのみ" },
                    new RentalList { PokemonName = "ユニラン", ItemName = "せんせいのツメ" },
                    new RentalList { PokemonName = "ムンナ", ItemName = "まがったスプーン" },
                    new RentalList { PokemonName = "メグロコ", ItemName = "キーのみ" },
                    new RentalList { PokemonName = "オタマロ", ItemName = "クラボのみ" },
                    new RentalList { PokemonName = "タマゲタケ", ItemName = "おおきなねっこ" },
                    new RentalList { PokemonName = "シママ", ItemName = "じしゃく" },
                    new RentalList { PokemonName = "チラーミィ", ItemName = "モモンのみ" },
                    new RentalList { PokemonName = "ギアル", ItemName = "しめつけバンド" },
                    new RentalList { PokemonName = "モノズ", ItemName = "ヤチェのみ" },
                    new RentalList { PokemonName = "ヤナップ", ItemName = "オボンのみ" },
                    new RentalList { PokemonName = "バオップ", ItemName = "イトケのみ" },
                    new RentalList { PokemonName = "ヒヤップ", ItemName = "クラボのみ" },
                    new RentalList { PokemonName = "デスマス", ItemName = "リュガのみ" },
                    new RentalList { PokemonName = "ゴビット", ItemName = "チイラのみ" },
                    new RentalList { PokemonName = "ドッコラー", ItemName = "ウタンのみ" },
                    new RentalList { PokemonName = "コアルヒー", ItemName = "するどいくちばし" },
                    new RentalList { PokemonName = "バニプッチ", ItemName = "ヤタピのみ" },
                    new RentalList { PokemonName = "テッシード", ItemName = "ゴツゴツメット" },
                    new RentalList { PokemonName = "クマシュン", ItemName = "オッカのみ" },
                    new RentalList { PokemonName = "チョボマキ", ItemName = "オボンのみ" },
                    new RentalList { PokemonName = "ツタージャ", ItemName = "しめつけバンド" },
                    new RentalList { PokemonName = "ポカブ", ItemName = "シュカのみ" },
                    new RentalList { PokemonName = "ミジュマル", ItemName = "ソクノのみ" },
                    new RentalList { PokemonName = "クルミル", ItemName = "ぎんのこな" },
                    new RentalList { PokemonName = "コロモリ", ItemName = "クラボのみ" },
                    new RentalList { PokemonName = "ダルマッカ", ItemName = "キーのみ" },
                    new RentalList { PokemonName = "カブルモ", ItemName = "バコウのみ" },
                    new RentalList { PokemonName = "バチュル", ItemName = "チイラのみ" },
                    new RentalList { PokemonName = "キバゴ", ItemName = "ヤチェのみ" },
                    new RentalList { PokemonName = "イシズマイ", ItemName = "ねらいのまと" },
                    new RentalList { PokemonName = "シビシラス", ItemName = "するどいキバ" },
                    new RentalList { PokemonName = "モグリュー", ItemName = "リンドのみ" },
                    new RentalList { PokemonName = "ヤブクロン", ItemName = "ウタンのみ" },
                    new RentalList { PokemonName = "ゾロア", ItemName = "くろいメガネ" },
                    new RentalList { PokemonName = "シキジカ", ItemName = "モモンのみ" },
                    new RentalList { PokemonName = "プルリル", ItemName = "オボンのみ" },
                    new RentalList { PokemonName = "リグレー", ItemName = "キーのみ" },
                    new RentalList { PokemonName = "コマタナ", ItemName = "ヨプのみ" },
                    new RentalList { PokemonName = "ズルッグ", ItemName = "オボンのみ" },
                    new RentalList { PokemonName = "ワシボン", ItemName = "するどいくちばし" },
                    new RentalList { PokemonName = "ワルビル", ItemName = "やわらかいすな" },
                    new RentalList { PokemonName = "プロトーガ", ItemName = "かいがらのすず" },
                    new RentalList { PokemonName = "ハトーボー", ItemName = "クラボのみ" },
                    new RentalList { PokemonName = "ホイーガ", ItemName = "バコウのみ" },
                    new RentalList { PokemonName = "メラルバ", ItemName = "カゴのみ" },
                    new RentalList { PokemonName = "ダブラン", ItemName = "きあいのハチマキ" },
                    new RentalList { PokemonName = "ランプラー", ItemName = "きゅうこん" },
                    new RentalList { PokemonName = "バルチャイ", ItemName = "クラボのみ" },
                    new RentalList { PokemonName = "ハーデリア", ItemName = "シルクのスカーフ" },
                    new RentalList { PokemonName = "クルマユ", ItemName = "オッカのみ" },
                    new RentalList { PokemonName = "ガマガル", ItemName = "リンドのみ" },
                    new RentalList { PokemonName = "ガントル", ItemName = "ゴツゴツメット" },
                    new RentalList { PokemonName = "ゴチミル", ItemName = "キーのみ" },
                    new RentalList { PokemonName = "バニリッチ", ItemName = "モモンのみ" },
                    new RentalList { PokemonName = "アーケン", ItemName = "ソクノのみり" },
                    new RentalList { PokemonName = "ミネズミ", ItemName = "するどいキバ" },
                    new RentalList { PokemonName = "フシデ", ItemName = "どくバリ" },
                    new RentalList { PokemonName = "マメパト", ItemName = "ピントレンズ" },
                    new RentalList { PokemonName = "ヨーテリー", ItemName = "シルクのスカーフ" },
                    new RentalList { PokemonName = "ヒトモシ", ItemName = "せんせいのツメ" },
                    new RentalList { PokemonName = "ダンゴロ", ItemName = "さらさらいわ" },
                    new RentalList { PokemonName = "モンメン", ItemName = "おおきなねっこ" },
                    new RentalList { PokemonName = "チュリネ", ItemName = "おはなのおこう" },
                    new RentalList { PokemonName = "コジョフー", ItemName = "ちからのハチマキ" },
                    new RentalList { PokemonName = "チョロネコ", ItemName = "するどいキバ" },
                    new RentalList { PokemonName = "ゴチム", ItemName = "ナモのみ" },
                    new RentalList { PokemonName = "ユニラン", ItemName = "	オボンのみ" },
                    new RentalList { PokemonName = "ムンナ", ItemName = "ものしりメガネ" },
                    new RentalList { PokemonName = "メグロコ", ItemName = "ちからのハチマキ" },
                    new RentalList { PokemonName = "オタマロ", ItemName = "しめったいわ" },
                    new RentalList { PokemonName = "タマゲタケ", ItemName = "ひかりのこな" },
                    new RentalList { PokemonName = "シママ", ItemName = "ふうせん" },
                    new RentalList { PokemonName = "チラーミィ", ItemName = "おうじゃのしるし" },
                    new RentalList { PokemonName = "ギアル", ItemName = "メタルコート" },
                    new RentalList { PokemonName = "モノズ", ItemName = "ちからのハチマキ" },
                    new RentalList { PokemonName = "ヤナップ", ItemName = "カムラのみ" },
                    new RentalList { PokemonName = "バオップ", ItemName = "チイラのみ" },
                    new RentalList { PokemonName = "ヒヤップ", ItemName = "かいがらのすず" },
                    new RentalList { PokemonName = "デスマス", ItemName = "のろいのおふだ" },
                    new RentalList { PokemonName = "ゴビット", ItemName = "ちからのハチマキ" },
                    new RentalList { PokemonName = "ドッコラー", ItemName = "ピントレンズ" },
                    new RentalList { PokemonName = "コアルヒー", ItemName = "ソクノのみ" },
                    new RentalList { PokemonName = "バニプッチ", ItemName = "つめたいいわ" },
                    new RentalList { PokemonName = "テッシード", ItemName = "ゴツゴツメット" },
                    new RentalList { PokemonName = "クマシュン", ItemName = "たつじんのおび" },
                    new RentalList { PokemonName = "チョボマキ", ItemName = "バコウのみ" },
                    new RentalList { PokemonName = "ツタージャ", ItemName = "きせきのタネ" },
                    new RentalList { PokemonName = "ポカブ", ItemName = "イトケのみ" },
                    new RentalList { PokemonName = "ミジュマル", ItemName = "リンドのみ" },
                    new RentalList { PokemonName = "クルミル", ItemName = "きあいのハチマキ" },
                    new RentalList { PokemonName = "コロモリ", ItemName = "するどいキバ" },
                    new RentalList { PokemonName = "ダルマッカ", ItemName = "シュカのみ" },
                    new RentalList { PokemonName = "カブルモ", ItemName = "ぎんのこな" },
                    new RentalList { PokemonName = "バチュル", ItemName = "カムラのみ" },
                    new RentalList { PokemonName = "キバゴ", ItemName = "ちからのハチマキ" },
                    new RentalList { PokemonName = "イシズマイ", ItemName = "ゴツゴツメット" },
                    new RentalList { PokemonName = "シビシラス", ItemName = "するどいツメ" },
                    new RentalList { PokemonName = "モグリュー", ItemName = "せんせいのツメ" },
                    new RentalList { PokemonName = "ヤブクロン", ItemName = "くろいヘドロ" },
                    new RentalList { PokemonName = "ゾロア", ItemName = "ものしりメガネ" },
                    new RentalList { PokemonName = "シキジカ", ItemName = "カムラのみ" },
                    new RentalList { PokemonName = "プルリル", ItemName = "かいがらのすず" },
                    new RentalList { PokemonName = "リグレー", ItemName = "せんせいのツメ" },
                    new RentalList { PokemonName = "コマタナ", ItemName = "ちからのハチマキ" },
                    new RentalList { PokemonName = "ズルッグ", ItemName = "ちからのハチマキ" },
                    new RentalList { PokemonName = "ワシボン", ItemName = "するどいキバ" },
                    new RentalList { PokemonName = "ワルビル", ItemName = "チイラのみ" },
                    new RentalList { PokemonName = "プロトーガ", ItemName = "リンドのみ" },
                    new RentalList { PokemonName = "ハトーボー", ItemName = "パワフルハーブ" },
                    new RentalList { PokemonName = "ホイーガ", ItemName = "くろいヘドロ" },
                    new RentalList { PokemonName = "メラルバ", ItemName = "ヨロギのみ" },
                    new RentalList { PokemonName = "ダブラン", ItemName = "せんせいのツメ" },
                    new RentalList { PokemonName = "ランプラー", ItemName = "きゅうこん" },
                    new RentalList { PokemonName = "バルチャイ", ItemName = "ものしりメガネ" },
                    new RentalList { PokemonName = "ハーデリア", ItemName = "きあいのハチマキ" },
                    new RentalList { PokemonName = "クルマユ", ItemName = "こうかくレンズ" },
                    new RentalList { PokemonName = "ガマガル", ItemName = "ものしりメガネ" },
                    new RentalList { PokemonName = "ガントル", ItemName = "ふうせん" },
                    new RentalList { PokemonName = "ゴチミル", ItemName = "まがったスプーン" },
                    new RentalList { PokemonName = "バニリッチ", ItemName = "つめたいいわ" },
                    new RentalList { PokemonName = "アーケン", ItemName = "ヤタピのみ" },
                };
                return PokemonList;
            }
        }
    }
}